"""add password

Revision ID: 3761441a6f8f
Revises: 980a52944f73
Create Date: 2022-04-23 00:12:47.238798

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3761441a6f8f'
down_revision = '980a52944f73'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
